%PlotDKLgamut
%uses data generated by CalibrateDKLcolours
%to plot out gamut of values in luminance and CIE colour values
%J Greenwood 2015

%% set up the file and the calibrated values from the monitor

clear all;

thisFile='PlotDKLgamut.m';
ThisDirectory=which(thisFile); ThisDirectory=ThisDirectory(1:end-length(thisFile));

%load calibrated colour values
WhichMonFile = strcat(ThisDirectory,'MonitorData/CalDataDiamondPlusRGB.mat');
load(WhichMonFile);%load('/Users/John/Documents/MATLAB/Calibration/MonitorData/OfficeCalDataRGB.mat');

%% set up the files

%load measured DKL files & concatenate values
ColConVal = [0.2 0.3 0.6 1.0 2.0]; %only set for one value of colour contrast at a time
ColConNum = 5;

%0.2 colcon
DKLfiles{1,1} = 'DKLcolvals_-1Lum_0.2Con.mat'; %-1 lum, 0.2 con
DKLfiles{2,1} = 'DKLcolvals_-0.4Lum_0.2Con.mat';
DKLfiles{3,1} = 'DKLcolvals_-0.3Lum_0.2Con.mat';
DKLfiles{4,1} = 'DKLcolvals_-0.2Lum_0.2Con.mat'; %-0.2 lum, 0.2 con
DKLfiles{5,1} = 'DKLcolvals_0.2Lum_0.2Con.mat';  %0.2 lum, 0.2 con
DKLfiles{6,1} = 'DKLcolvals_0.3Lum_0.2Con.mat';
DKLfiles{7,1} = 'DKLcolvals_0.4Lum_0.2Con.mat';
DKLfiles{8,1} = 'DKLcolvals_1Lum_0.2Con.mat'; %1 lum, 0.2con

NumLum(1) = 8;
LumVals{1}   = [-1 -0.4 -0.3 -0.2 0.2 0.3 0.4 1];
LumInd{1}    = [1 2 3 4 5 6 7 8];

%0.3 colcon
DKLfiles{4,2} = 'DKLcolvals_-0.2Lum_0.3Con.mat'; %-0.2 lum, 0.2 con
DKLfiles{5,2} = 'DKLcolvals_0.2Lum_0.3Con.mat';  %0.2 lum, 0.2 con

NumLum(2) = 2;
LumVals{2}   = [-0.2 0.2];
LumInd{2}    = [4 5];

%0.6 colcon
DKLfiles{4,3} = 'DKLcolvals_-0.2Lum_0.6Con.mat'; %-0.2 lum, 0.6 con
DKLfiles{5,3} = 'DKLcolvals_0.2Lum_0.6Con.mat';  %0.2 lum, 0.6 con

NumLum(3)     = 2;
LumVals{3}    = [-0.2 0.2];
LumInd{3}     = [4 5]; %only take certain values

%1 colcon
DKLfiles{1,4} = 'DKLcolvals_-1Lum_1Con.mat'; %-0.2 lum, 0.6 con
DKLfiles{6,4} = 'DKLcolvals_1Lum_1Con.mat';  %0.2 lum, 0.6 con

NumLum(4)     = 2;
LumVals{4}    = [-1 1];
LumInd{4}     = [1 6]; %only take certain values

%2 colcon - ridiculous value outside of DKL space but allows better encapsulation of the full RGB gamut of the monitor
DKLfiles{1,5} = 'DKLcolvals_-2Lum_2Con.mat'; %-0.2 lum, 0.6 con

NumLum(5)     = 1;
LumVals{5}    = -2;
LumInd{5}     = 1; %only take certain values


%% now load the data

AllDKL.Allx = []; %create blank array
AllDKL.Ally = [];

for colcon = 1:ColConNum
    for lv=1:NumLum(colcon)
        WhichL = LumInd{colcon}(lv);
        load(strcat(ThisDirectory,'MonitorData/DiamondPlusRGBgamut/',DKLfiles{WhichL,colcon}));
        
        AllDKL.LV{colcon}(lv)          = LV;
        AllDKL.HueAngles{colcon}(lv,:) = HueAngles;
        AllDKL.RGBval{colcon}(:,:,lv)  = DKL.RGBval;
        AllDKL.LumVals{colcon}(lv,:)   = DKL.LumVals;
        AllDKL.cXvals{colcon}(lv,:)    = DKL.cXvals;
        AllDKL.cYvals{colcon}(lv,:)    = DKL.cYvals;
        AllDKL.cZvals{colcon}(lv,:)    = DKL.cZvals;
        AllDKL.IsReal{colcon}(:,:,lv)  = DKL.IsReal;
        AllDKL.Allx                    = [AllDKL.Allx DKL.cXvals];
        AllDKL.Ally                    = [AllDKL.Ally DKL.cYvals];
    end
end

%% now plot things

MarkerTypes = {'o','s','^','d','v','>','<','*'};

figure
cnt=1;
for colcon=1:ColConNum
    subplot(2,ColConNum,cnt); %plot luminance values
    for lv = 1:NumLum(colcon)
        plot(rad2deg(-AllDKL.HueAngles{colcon}(lv,:)),AllDKL.LumVals{colcon}(lv,:),'k-'); %draw the line
        hold on;
        for hue=1:numel(AllDKL.HueAngles{colcon}(lv,:)) %draw individual points
            h(lv)=plot(rad2deg(-AllDKL.HueAngles{colcon}(lv,hue)),AllDKL.LumVals{colcon}(lv,hue),'Marker',MarkerTypes{lv},'Color',AllDKL.RGBval{colcon}(hue,:,lv)./255,'MarkerFaceColor',AllDKL.RGBval{colcon}(hue,:,lv)./255);
        end
        %plot(xlim,[LumVal(lv) LumVal(lv)]);
    end
    title(strcat('Luminance values for ',num2str(ColConVal(colcon)),' Col Con'));
    xlabel('Hue Angle (deg)')
    ylabel('Luminance (cd/m2)');
    axis square
    legend(h,num2str(AllDKL.LV{colcon}'));
    cnt=cnt+1;
    xlim([0 360]);
    xtick(0:90:360);
    ylim([20 90]);
end
for colcon=1:ColConNum
    subplot(2,ColConNum,cnt);
    for lv=1:NumLum(colcon)
        h(lv) = plot(AllDKL.cXvals{colcon}(lv,:),AllDKL.cYvals{colcon}(lv,:),'k-'); %draw the line
        hold on;
        for hue=1:numel(AllDKL.HueAngles{colcon}(lv,:))
            h(lv)=plot(AllDKL.cXvals{colcon}(lv,hue),AllDKL.cYvals{colcon}(lv,hue),'Marker',MarkerTypes{lv},'Color',AllDKL.RGBval{colcon}(hue,:,lv)./255,'MarkerFaceColor',AllDKL.RGBval{colcon}(hue,:,lv)./255);
        end
    end
    title(strcat('CIE Chromaticities for ',num2str(ColConVal(colcon)),' Col Con'));
    xlabel('X vals');
    ylabel('Y vals');
    axis square;
    legend(h,num2str(AllDKL.LV{colcon}'));
    cnt=cnt+1;
    xlim([0.05 0.65]);
    xtick(0.1:0.1:0.6);
    ylim([0.05 0.65]);
    ytick(0.1:0.1:0.6);
end

figure
cnt=1;
for colcon=1:ColConNum
    for lv = 1:NumLum(colcon)
        subplot(3,ceil(sum(NumLum)/3),cnt)
        
        h(lv)=plot(rad2deg(-AllDKL.HueAngles{colcon}(lv,:)),AllDKL.cXvals{colcon}(lv,:),'r-','Marker',MarkerTypes{lv}); %
        hold on;
        plot(rad2deg(-AllDKL.HueAngles{colcon}(lv,:)),AllDKL.cYvals{colcon}(lv,:),'g-','Marker',MarkerTypes{lv}); %
        plot(rad2deg(-AllDKL.HueAngles{colcon}(lv,:)),AllDKL.cZvals{colcon}(lv,:),'b-','Marker',MarkerTypes{lv}); %
        title(strcat('Chroma vs hue for',num2str(ColConVal(colcon)),' Col Con, ',num2str(LumVals{colcon}(lv)),' Lum'));
        xlabel('Hue angle (deg)');
        ylabel('Chromaticity value (CIE)');
        axis square;
        legend(h,num2str(AllDKL.LV{colcon}'));
        cnt=cnt+1;
    end
end

WikiGamutX = [0.6400 0.3000 0.1500 0.6400]; %typical sRGB gamut in CIE coordinates (from wikipedia)
WikiGamutY = [0.3300 0.6000 0.0600 0.3300];
MaxValsX   = [0.631 0.2888 0.1410 0.631];% max x chromaticity values for each RGBR gun at 50% luminance, measured during calibration
MaxValsY   = [0.346 0.5920 0.0690 0.346];% max y values
D65valX    = 0.3127; %standardised D65 white value
D65valY    = 0.329;
OurD65X    = 0.320;%0.315;%
OurD65Y    = 0.333;%0.331;%

%now try to work out the whole CRT gamut based on all the above X,Y values
figure
plot(AllDKL.Allx,AllDKL.Ally,'o','Color',[0 0 0],'MarkerFaceColor',[0 0 0]);
hold on;
hull = convhull(AllDKL.Allx,AllDKL.Ally);
plot(AllDKL.Allx(hull), AllDKL.Ally(hull), '-r');
plot(MaxValsX,MaxValsY,'-b');
plot(OurD65X,OurD65Y,'ko');
%plot(D65valX,D65valY,'k^');
title('CIE Chromaticities for all values');
xlabel('X vals');
ylabel('Y vals');
axis square;
xlim([0 0.65]);
xtick(0:0.1:0.6);
ylim([0 0.65]);
ytick(0:0.1:0.6);

